name: 'deploy'
description: 'Deploys the application'

inputs:
  env-name:
    description: Name of the environment being deployed
    required: true

  app-env:
    description: Value of the NX_APP_ENV environment variable
    required: false
    default: 'test'

  aws-access-key-id:
    description: AWS Access Key ID
    required: true

  aws-secret-access-key:
    description: AWS Secret Access Key
    required: true

  do-storybook:
    description: Whether to deploy storybook
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Download Dist folder
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist

    - name: Deploy Backend Stack
      shell: bash
      run: yarn nx deploy-${{ inputs.env-name }}-backend web-app
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_REGION: us-east-1

    - name: Get Pool Id
      shell: bash
      run: echo "USERPOOL_ID=$(cat apps/web-app/public/app-config.json | jq --raw-output 'keys[] as $k | .[$k] | .UserPoolId')" >> $GITHUB_ENV

    - name: Rebuild with baked in environment variables
      shell: bash
      run: rm -rf dist && yarn nx build web-app
      env:
        NX_USER_POOL_ID: ${{ env.USERPOOL_ID }}

    - name: Process build artifact for Serverless
      shell: bash
      run: yarn ts-node tools/build-serverless-next.ts

    - name: Deploy Application Stack
      shell: bash
      run: yarn nx deploy-${{ inputs.env-name }} web-app
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_REGION: us-east-1

    - name: Get Deploy Bucket
      shell: bash
      run: echo "BUCKET=$(cat apps/web-app/public/app-config.json | jq --raw-output '."tnm-web-${{ inputs.env-name }}-stack" | .DeployBucket')" >> $GITHUB_ENV

    - name: Upload App Config
      uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ inputs.aws-access-key-id }}
        aws_secret_access_key: ${{ inputs.aws-secret-access-key }}
        aws_bucket: ${{ env.BUCKET }}
        source_dir: apps/web-app/public
        destination_dir: ''

    - name: Download Storybook
      uses: actions/download-artifact@v3
      if: ${{ inputs.do-storybook == 'true' }}
      with:
        name: storybook
        path: storybook

    - name: Upload Storybook
      uses: shallwefootball/s3-upload-action@master
      if: ${{ inputs.do-storybook == 'true' }}
      with:
        aws_key_id: ${{ inputs.aws-access-key-id }}
        aws_secret_access_key: ${{ inputs.aws-secret-access-key }}
        aws_bucket: ${{ env.BUCKET }}
        source_dir: storybook
        destination_dir: 'storybook'
