export const USER_POOL_ID_ENV_KEY_STRING = 'USERPOOL_ID';
export const SEED_USERS_ENV_KEY_STRING = 'SEED_USERS';
export const SEED_DATA_BUCKET_KEY_STRING = 'SEED_DATA_BUCKET';
export const SEED_DATA_FILE_NAME = 'seed-data.json';
