name: 'setup-node-job'
description: 'Sets up jobs running on node'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: key-again-${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Cache Cypress Binary
      id: cache-cypress-binary
      uses: actions/cache@v3
      with:
        path: cypress/cache
        key: cypress-binary-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      shell: 'bash'
      run: yarn install --frozen-lockfile
      env:
        CYPRESS_CACHE_FOLDER: cypress/cache
