name: 'setup-node-job'
description: 'Sets up jobs running on node'

inputs:
  cache-node-modules:
    description: Whether to cache the node_modules directory in this job
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Configure node 14
      uses: actions/setup-node@v3
      if: ${{ inputs.cache-node-modules != 'true' }}
      with:
        node-version: '14'
        cache: 'yarn'

    - name: Configure node 14
      uses: actions/setup-node@v3
      if: ${{ inputs.cache-node-modules == 'true' }}
      with:
        node-version: '14'

    - name: Cache node_modules
      if: ${{ inputs.cache-node-modules == 'true' }}
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-build-cache-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-cache-
          ${{ runner.os }}-

    - name: Install dependencies
      shell: 'bash'
      run: yarn install --frozen-lockfile
