name: 'setup-node-job'
description: 'Sets up jobs running on node'

runs:
  using: 'composite'
  steps:
    - name: Configure node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'

    - name: Install dependencies
      shell: 'bash'
      run: yarn install --frozen-lockfile
