name: Test and Deploy
concurrency:
  group: mainline
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  static-checks:
    name: Run Static Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - planner
          - seed-cognito
          - constants

        target:
          - test
          - lint

    steps:
      - uses: actions/checkout@v3

      - name: Setup node environment
        uses: ./.github/actions/setup-node-job

      - name: Run ${{ matrix.target }}
        run: yarn nx ${{ matrix.target }} ${{ matrix.project }}

  build-next-app:
    name: Build NextJS app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node environment
        uses: ./.github/actions/setup-node-job

      - name: Run
        run: yarn nx build web-app

  build-storybook:
    name: Build Storybook
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node environment
        uses: ./.github/actions/setup-node-job

      - name: Run
        run: yarn nx run components:build-storybook

      - name: Save Artifact
        uses: actions/upload-artifact@v3
        with:
          name: storybook
          path: dist/storybook/components

  deploy-for-cypress:
    name: Cypress Deploy
    runs-on: ubuntu-latest
    needs: [build-next-app]

    steps:
      - uses: actions/checkout@v3

      - name: Setup node environment
        uses: ./.github/actions/setup-node-job

      - name: Regenerate build from cache
        run: yarn nx build web-app

      - name: Deploy
        run: yarn nx deploy-cypress web-app
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Get S3 Bucket
        run: echo "UPLOAD_BUCKET=$(cat apps/web-app/public/app-config.json | jq --raw-output 'keys[] as $k | .[$k] | .StaticsBucket')" >> $GITHUB_ENV

      - name: Upload Next Statics
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ env.UPLOAD_BUCKET }}
          destination_dir: _next/static
          source_dir: dist/apps/web-app/.next/static

      - name: Upload App Config
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ env.UPLOAD_BUCKET }}
          source_dir: apps/web-app/public
          destination_dir: ''

      - name: Download Storybook
        uses: actions/download-artifact@v3
        with:
          name: storybook
          path: storybook

      - name: Upload Storybook
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ env.UPLOAD_BUCKET }}
          source_dir: storybook
          destination_dir: 'storybook'

      - name: Get Cloudfront ID
        run: echo "CLOUDFRONT_ID=$(cat apps/web-app/public/app-config.json | jq --raw-output 'keys[] as $k | .[$k] | .CloudfrontId')" >> $GITHUB_ENV

      - name: Invalidate Cloudfront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ env.CLOUDFRONT_ID }}
          PATHS: /*
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  cypress-run:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [deploy-for-cypress]
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node environment
        uses: ./.github/actions/setup-node-job

      - name: Run E2E tests
        run: yarn nx run web-app-e2e:e2e --baseUrl=https://cypress.app.thenutritionistmcr.com --skipServe=true --skip-nx-cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NX_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          NX_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          NX_GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          NX_CHARGEBEE_TOKEN: ${{ secrets.CHARGEBEE_TOKEN }}
          NX_COGNITO_POOL_ID: us-east-1_ilYruIOKK

  deploy-for-test:
    name: Test Deploy
    runs-on: ubuntu-latest
    needs: [build-next-app, static-checks, cypress-run, build-storybook]

    steps:
      - uses: actions/checkout@v3

      - name: Setup node environment
        uses: ./.github/actions/setup-node-job

      - name: Regenerate build from cache
        run: yarn nx build web-app

      - name: Deploy
        run: yarn nx deploy-test web-app
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Get S3 Bucket
        run: echo "UPLOAD_BUCKET=$(cat apps/web-app/public/app-config.json | jq --raw-output 'keys[] as $k | .[$k] | .StaticsBucket')" >> $GITHUB_ENV

      - name: Upload Next Statics
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ env.UPLOAD_BUCKET }}
          destination_dir: _next/static
          source_dir: dist/apps/web-app/.next/static

      - name: Upload App Config
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ env.UPLOAD_BUCKET }}
          source_dir: apps/web-app/public
          destination_dir: ''

      - name: Download Storybook
        uses: actions/download-artifact@v3
        with:
          name: storybook
          path: storybook

      - name: Upload Storybook
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ env.UPLOAD_BUCKET }}
          source_dir: storybook
          destination_dir: 'storybook'

      - name: Get Cloudfront ID
        run: echo "CLOUDFRONT_ID=$(cat apps/web-app/public/app-config.json | jq --raw-output 'keys[] as $k | .[$k] | .CloudfrontId')" >> $GITHUB_ENV

      - name: Invalidate Cloudfront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ env.CLOUDFRONT_ID }}
          PATHS: /*
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-for-dev:
    name: Dev Deploy
    runs-on: ubuntu-latest
    needs: [build-next-app, build-storybook]

    steps:
      - uses: actions/checkout@v3

      - name: Setup node environment
        uses: ./.github/actions/setup-node-job

      - name: Regenerate build from cache
        run: yarn nx build web-app

      - name: Deploy
        run: yarn nx deploy-dev web-app
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Get S3 Bucket
        run: echo "UPLOAD_BUCKET=$(cat apps/web-app/public/app-config.json | jq --raw-output 'keys[] as $k | .[$k] | .StaticsBucket')" >> $GITHUB_ENV

      - name: Upload Next Statics
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ env.UPLOAD_BUCKET }}
          destination_dir: _next/static
          source_dir: dist/apps/web-app/.next/static

      - name: Upload App Config
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ env.UPLOAD_BUCKET }}
          source_dir: apps/web-app/public
          destination_dir: ''

      - name: Download Storybook
        uses: actions/download-artifact@v3
        with:
          name: storybook
          path: storybook

      - name: Upload Storybook
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ env.UPLOAD_BUCKET }}
          source_dir: storybook
          destination_dir: 'storybook'

      - name: Get Cloudfront ID
        run: echo "CLOUDFRONT_ID=$(cat apps/web-app/public/app-config.json | jq --raw-output 'keys[] as $k | .[$k] | .CloudfrontId')" >> $GITHUB_ENV

      - name: Invalidate Cloudfront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ env.CLOUDFRONT_ID }}
          PATHS: /*
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-for-prod:
    name: Production Deploy
    runs-on: ubuntu-latest
    needs: [build-next-app, static-checks, cypress-run, build-storybook]

    steps:
      - uses: actions/checkout@v3

      - name: Setup node environment
        uses: ./.github/actions/setup-node-job

      - name: Regenerate build from cache
        run: yarn nx build web-app
        env:
          NX_APP_ENV: production

      - name: Deploy
        run: yarn nx deploy-prod web-app
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Get S3 Bucket
        run: echo "UPLOAD_BUCKET=$(cat apps/web-app/public/app-config.json | jq --raw-output 'keys[] as $k | .[$k] | .StaticsBucket')" >> $GITHUB_ENV

      - name: Upload Next Statics
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ env.UPLOAD_BUCKET }}
          destination_dir: _next/static
          source_dir: dist/apps/web-app/.next/static

      - name: Upload App Config
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ env.UPLOAD_BUCKET }}
          source_dir: apps/web-app/public
          destination_dir: ''

      - name: Download Storybook
        uses: actions/download-artifact@v3
        with:
          name: storybook
          path: storybook

      - name: Upload Storybook
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ env.UPLOAD_BUCKET }}
          source_dir: storybook
          destination_dir: 'storybook'

      - name: Get Cloudfront ID
        run: echo "CLOUDFRONT_ID=$(cat apps/web-app/public/app-config.json | jq --raw-output 'keys[] as $k | .[$k] | .CloudfrontId')" >> $GITHUB_ENV

      - name: Invalidate Cloudfront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ env.CLOUDFRONT_ID }}
          PATHS: /*
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
