name: Test and Deploy
concurrency:
  group: mainline
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  static-checks:
    name: Run Static Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - web-app
          - components
          - verify-jwt

        target:
          - test
          - lint

    steps:
      - uses: actions/checkout@v2

      - name: Configure node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: 'yarn'

      - name: Cache Nx
        uses: actions/cache@v2
        with:
          path: node_modules/.cache/nx
          key: cache-nx-${{ hashFiles('yarn.lock') }}-${{ github.sha }}
          restore-keys: |
            cache-nx-${{ hashFiles('yarn.lock') }}-

      - name: Install Dependencies
        run: yarn install

      - name: Run all unit tests
        run: yarn nx ${{ matrix.target }} ${{ matrix.project }}
