name: Test and Deploy
concurrency:
  group: mainline
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - './docs'

jobs:
  deploy-permissions-changes:
    name: Deploy Permissions Changes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node environment
        uses: ./.github/actions/setup-node-job

      - name: Deploy
        shell: bash
        run: yarn nx deploy:users
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-2
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}

  static-checks:
    name: Run Static Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - planner
          - seed-cognito
          - constants
          - utils
          - web-app

        target:
          - test
          - lint

    steps:
      - uses: actions/checkout@v3

      - name: Setup node environment
        uses: ./.github/actions/setup-node-job

      - name: Run ${{ matrix.target }}
        run: yarn nx ${{ matrix.target }} ${{ matrix.project }}

  build-next-app:
    name: Build NextJS app
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        env:
          - dev
          - cypress
          - prod
          - test
    steps:
      - uses: actions/checkout@v3

      - name: Setup node environment
        uses: ./.github/actions/setup-node-job

      - name: Get App Version
        shell: bash
        run: echo "APP_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Application
        run: yarn nx build web-app && yarn nx export web-app
        env:
          NX_APP_VERSION: ${{ matrix.env }}

      - name: Save dist folder
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.env }}
          path: dist

  build-storybook:
    name: Build Storybook
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node environment
        uses: ./.github/actions/setup-node-job

      - name: Run
        run: yarn nx run components:build-storybook

      - name: Save Artifact
        uses: actions/upload-artifact@v3
        with:
          name: storybook
          path: dist/storybook/components

  deploy-for-cypress:
    name: Cypress Deploy
    runs-on: ubuntu-latest
    needs: [build-next-app]

    steps:
      - uses: actions/checkout@v3

      - name: Setup node environment
        uses: ./.github/actions/setup-node-job

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          do-hotswap: true
          seed: true
          env-name: cypress
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          datadog-app-id: ${{ secrets.DATADOG_APP_ID }}
          datadog-client-token: ${{ secrets.DATADOG_CLIENT_TOKEN }}
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          url: https://cypress.app.thenutritionistmcr.com

  cypress-run:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [deploy-for-cypress]
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node environment
        uses: ./.github/actions/setup-node-job
        with:
          cache-node-modules: false

      - name: Run E2E tests
        run: yarn nx run web-app-e2e:e2e --baseUrl=https://cypress.app.thenutritionistmcr.com --skipServe=true --skip-nx-cache
        continue-on-error: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NX_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          NX_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          NX_GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          NX_CHARGEBEE_TOKEN: ${{ secrets.CHARGEBEE_TOKEN }}
          NX_COGNITO_POOL_ID: eu-west-2_77z37j3Fb

      - name: Copy execution videos
        run: |
          mkdir docs
          cp -r dist/cypress/apps/web-app-e2e/videos cos/videos

      - name: Merge test results into one
        run: yarn report:merge

      - name: Generate HTML test report
        run: yarn report:generate

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          user_name: 'github-actions[bot]'
          user_email: actions[bot]@users.noreply.github.com

  deploy-for-test:
    name: Test Deploy
    runs-on: ubuntu-latest
    needs: [build-next-app, static-checks, cypress-run, build-storybook]

    steps:
      - uses: actions/checkout@v3

      - name: Setup node environment
        uses: ./.github/actions/setup-node-job

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          env-name: test
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          datadog-app-id: ${{ secrets.DATADOG_APP_ID }}
          datadog-client-token: ${{ secrets.DATADOG_CLIENT_TOKEN }}
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          url: https://test.app.thenutritionistmcr.com

  deploy-for-dev:
    name: Dev Deploy
    runs-on: ubuntu-latest
    needs: [build-next-app, build-storybook]

    steps:
      - uses: actions/checkout@v3

      - name: Setup node environment
        uses: ./.github/actions/setup-node-job

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          env-name: dev
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          datadog-app-id: ${{ secrets.DATADOG_APP_ID }}
          datadog-client-token: ${{ secrets.DATADOG_CLIENT_TOKEN }}
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          url: https://dev.app.thenutritionistmcr.com

  deploy-for-prod:
    name: Production Deploy
    runs-on: ubuntu-latest
    needs: [build-next-app, static-checks, cypress-run, build-storybook]

    steps:
      - uses: actions/checkout@v3

      - name: Setup node environment
        uses: ./.github/actions/setup-node-job

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          env-name: prod
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          app-env: production
          datadog-app-id: ${{ secrets.DATADOG_APP_ID }}
          datadog-client-token: ${{ secrets.DATADOG_CLIENT_TOKEN }}
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          url: https://portal.thenutritionistmcr.com
