name: Manually run Cypress tests

on:
  workflow_dispatch:

env:
  CYPRESS_CACHE_FOLDER: cypress/cache

jobs:
  cypress-run:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [deploy-for-cypress]
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: env

      - name: Setup node environment
        uses: ./.github/actions/setup-node-job

      - name: Run E2E tests
        run: yarn nx run web-app-e2e:e2e --baseUrl=https://cypress.app.thenutritionistmcr.com --skipServe=true --skip-nx-cache
        # continue-on-error: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NX_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          NX_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          NX_GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          NX_CHARGEBEE_TOKEN: ${{ secrets.CHARGEBEE_TOKEN }}
          NX_COGNITO_POOL_ID: eu-west-2_77z37j3Fb
