name: Manually run Cypress tests

on:
  workflow_dispatch:

jobs:
  cypress-run:
    name: E2E Tests
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Run E2E tests
        run: yarn nx run web-app-e2e:e2e --baseUrl=https://cypress.app.thenutritionistmcr.com --skipServe=true
        env:
          NX_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          NX_GOOGLE_CLIENT_SECRT: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          NX_GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          NX_CHARGEBEE_TOKEN: ${{ secrets.CHARGEBEE_TOKEN }}
          NX_COGNITO_POOL_ID: eu-west-2_X1GcrUCJu
