name: Manually run Cypress tests

on:
  workflow_dispatch:

jobs:
  cypress-run:
    name: E2E Tests
    runs-on: ubuntu-latest
    container: bwainwrighttnm/cypress:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node environment
        uses: ./.github/actions/setup-node-job

      - name: Run E2E tests
        uses: ./.github/actions/cypress
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          google-refresh-token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          chargebee-token: ${{ secrets.CHARGEBEE_TOKEN }}
          cognito-pool-id: eu-west-2_77z37j3Fb
          github-token: ${{ secrets.GITHUB_TOKEN }}
